services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - protrait
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  dicom-sorter:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: .
    container_name: dicom-sorter
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "104:104"
    networks:
      - protrait
    volumes:
      - ./associationdata:/dicomsorter/data
  dvh-calculator:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # image: ghcr.io/mdw-nl/dvh_consumer:roi-combination-work
    image: dvh-calculator:latest
    container_name: dvh-calculator
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
      - ./associationdata:/dicomsorter/data
    networks:
      - protrait
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - protrait
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
networks:
  protrait:
    driver: bridge

