services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - protrait
  dicom-sorter:
    build: .
    container_name: dicom-sorter
    depends_on:
      - postgres
    ports:
      - "104:104"
    networks:
      - protrait
    volumes:
      - /Users/alessioromita/Documents/data_test_docker:/dicomsorter/data
  dvh-calculator:
    image: ghcr.io/mdw-nl/dvh_consumer:roi-combination-work
    container_name: dvh-calculator
    depends_on:
      - postgres
    networks:
      - protrait
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - protrait

networks:
  protrait:
    driver: bridge

