services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - protrait
  dicomsorter:
    build: .
    depends_on:
      - postgres
    ports:
      - "104:104"
    networks:
      - protrait
networks:
  protrait:
    driver: bridge
