services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - protrait
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  dicom-listener:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: .
    container_name: dicom-listener
    command: uv run python main.py
    environment:
      - PYTHONUNBUFFERED=1
      - USE_PACS=${USE_PACS:-true}
      - PACS_CRON_INTERVAL=${PACS_CRON_INTERVAL:-300}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "104:104"
    networks:
      - protrait
    volumes:
      - ./associationdata:/dicomsorter/data
      - ./anonymization/recipes:/recipes

  dicom-api:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    container_name: dicom-api
    command: uv run uvicorn dicomsorter.api:app --host 0.0.0.0 --port 9000
    environment:
      - PYTHONUNBUFFERED=1
      - USE_RABBITMQ=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
    networks:
      - protrait
    volumes:
      - ./associationdata:/dicomsorter/data
      - ./anonymization/recipes:/recipes

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - protrait
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   networks:
  #     - protrait
  #   ports:
  #     - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:9.2.1
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=kibana
  #     - ELASTICSEARCH_PASSWORD=kibana
  #     - xpack.security.enabled=false
  #   networks:
  #     - protrait
  #   ports:
  #     - "5601:5601"
networks:
  protrait:
    driver: bridge
