postgres:
    host: "host.docker.internal"
    port: "5432"
    username: "postgres"
    password: "postgres"
    db: "postgres"
rabbitMQ:
  host: "host.docker.internal"
  port: "5672"
  username: "guest"
  password: "guest"
  queue_name: "DICOM_Processor"
