postgres:
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: "postgres"
  db: "postgres"
rabbitMQ:
  host: "rabbitmq"
  port: "5672"
  username: "user"
  password: "password"
  queue_name: "DICOM_Processor"
  anonymizer_queue_name: "DICOM_Anonymizer"
  xnat_queue_name: "DICOM_XNAT"
  use_anonymizer: true
