postgres:
    host: "${MY_VARIABLE}"
    port: "5432"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    db: "${POSTGRES_DB}"
rabbitMQ:
  host: "host.docker.internal"
  port: "5672"
  username: "user"
  password: "password"
  queue_name: "DICOM_Processor"
